# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 04688738ef5f620fffc8aad0708a8a8ea35645c36267a5f4554c9eaf17c2198097b1c89ea629c01858ffa30d8c59951f15198b7624e4929b2acc755ff9b4fc1c

test:
  secret_key_base: 97f514aa272d2f9b824b9c849e7a5f3a462659a339fb299f19b75ada579df44900259a5ed80b62d3c0c8471833ebefc928d9f37faf2bb83dc828c4dfcce0d48f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
